// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
<<<<<<< HEAD
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//     shadowDatabaseUrl: process.env["DIRECT_URL"],
//   },
// });

import { defineConfig } from "prisma/config";
import "dotenv/config";

export default defineConfig({
  schema: "prisma/schema.prisma",

  datasource: {
    url: process.env.DATABASE_URL, 
  },
});
=======
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
>>>>>>> 19eef18d92562398c621f7b625224cc0b9671b49
